export const ApiEndPoints = {
  login: "api/login",
  forgotPassword: "/api/users/updatePassword",
  amenities: "api/amenities",
  users: "/api/users",
  categories: "/api/categories",
  categoriesAdd: "/api/categories/admin/add",
  stays: "/api/stays/admin/add",
  categoriesDelete: "/api/categories/admin/delete",
  //locations: "/api/locations/admin/",
  getLocation: "/api/locations/admin/getAll",
  getLocationById: "/api/locations/admin/",
  deleteLocation: "/api/locations/admin/delete/",
  updateLocation: "/api/locations/admin/update",
  adminAddLocation: "/api/locations/admin/add",
  allStay: "/api/stays/admin/getStaysList",
  stayById: "/api/stays/admin/findByStayId",
  deleteStay: "/api/stays/admin/delete/",
  //locationById: "/api/locations/admin/",
};
